sudo: false
jdk:
    - oraclejdk8
language: android
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # to install Android SDK tools 25.1.x (x = 6 right now)
    - build-tools-25.0.3
    - android-25
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

script: ./gradlew clean check assembleDebug
